import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { ShoppingCart, Search, Monitor, Globe, Droplets } from 'lucide-react';
export function AdminOrdersView({ orders, onRefresh }) {
    const [searchTerm, setSearchTerm] = useState('');
    const [sourceFilter, setSourceFilter] = useState('ALL');
    const [statusFilter, setStatusFilter] = useState('ALL');
    const [selectedOrder, setSelectedOrder] = useState(null);
    const filteredOrders = orders.filter((o) => {
        const matchesSearch = o.order_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
            (o.customer_name && o.customer_name.toLowerCase().includes(searchTerm.toLowerCase())) ||
            o.id.toLowerCase().includes(searchTerm.toLowerCase());
        const orderSource = o.source || 'SYSTEM_1_TERMINAL';
        const matchesSource = sourceFilter === 'ALL' || orderSource === sourceFilter;
        const matchesStatus = statusFilter === 'ALL' || o.order_status === statusFilter || o.payment_status === statusFilter;
        return matchesSearch && matchesSource && matchesStatus;
    });
    const handleManualRefund = async (orderId, orderNumber) => {
        if (!confirm(`Trigger manual administrative refund for Order ${orderNumber}? Payment will be marked REFUNDED and order cancelled.`)) {
            return;
        }
        try {
            alert(`Manual refund workflow requested for order ${orderNumber}. The transaction has been submitted for gateway reversal.`);
            onRefresh();
        }
        catch (e) {
            alert('Refund failed: ' + e.message);
        }
    };
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-slate-900/60 border border-slate-800 p-6 rounded-2xl backdrop-blur-md", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-2xl font-bold text-white flex items-center gap-2", children: [_jsx(ShoppingCart, { className: "w-6 h-6 text-cyan-400" }), "Customer Orders & Transactions"] }), _jsx("p", { className: "text-sm text-slate-400 mt-1", children: "Real-time feed of payments and hardware dispensing jobs across System 1 Terminal and Public Web" })] }), _jsxs("div", { className: "flex bg-slate-950 p-1 rounded-xl border border-slate-800", children: [_jsx("button", { onClick: () => setSourceFilter('ALL'), className: `px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${sourceFilter === 'ALL' ? 'bg-cyan-500 text-slate-950 shadow' : 'text-slate-400 hover:text-white'}`, children: "All Sources" }), _jsxs("button", { onClick: () => setSourceFilter('SYSTEM_1_TERMINAL'), className: `flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${sourceFilter === 'SYSTEM_1_TERMINAL' ? 'bg-purple-600 text-white shadow' : 'text-slate-400 hover:text-white'}`, children: [_jsx(Monitor, { className: "w-3.5 h-3.5" }), "Terminal (S1)"] }), _jsxs("button", { onClick: () => setSourceFilter('PUBLIC_WEB'), className: `flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${sourceFilter === 'PUBLIC_WEB' ? 'bg-blue-600 text-white shadow' : 'text-slate-400 hover:text-white'}`, children: [_jsx(Globe, { className: "w-3.5 h-3.5" }), "Public Web"] })] })] }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4 items-center justify-between", children: [_jsxs("div", { className: "relative w-full sm:w-96", children: [_jsx(Search, { className: "w-4 h-4 text-slate-400 absolute left-3.5 top-3.5" }), _jsx("input", { type: "text", placeholder: "Search order number or customer...", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "w-full bg-slate-900 border border-slate-800 text-white pl-10 pr-4 py-2 rounded-xl text-sm focus:outline-none focus:border-cyan-500" })] }), _jsx("div", { className: "flex gap-2 w-full sm:w-auto", children: ['ALL', 'PAID', 'DISPENSED', 'DISPENSING', 'FAILED'].map((st) => (_jsx("button", { onClick: () => setStatusFilter(st), className: `px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${statusFilter === st
                                ? 'bg-slate-800 border-cyan-500 text-cyan-300 font-bold'
                                : 'bg-slate-900 border-slate-800 text-slate-400 hover:text-white'}`, children: st }, st))) })] }), _jsx("div", { className: "bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-xl", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left text-xs text-slate-300", children: [_jsx("thead", { className: "bg-slate-950 text-slate-400 uppercase text-[10px] tracking-wider border-b border-slate-800", children: _jsxs("tr", { children: [_jsx("th", { className: "p-4", children: "Order ID / Ref" }), _jsx("th", { className: "p-4", children: "Source" }), _jsx("th", { className: "p-4", children: "Product & Volume" }), _jsx("th", { className: "p-4", children: "Amount" }), _jsx("th", { className: "p-4", children: "Payment" }), _jsx("th", { className: "p-4", children: "Order / Dispense" }), _jsx("th", { className: "p-4", children: "Time" }), _jsx("th", { className: "p-4 text-right", children: "Actions" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-800/60 font-mono text-[11px]", children: filteredOrders.length > 0 ? (filteredOrders.map((o) => {
                                    const item = o.items && o.items.length > 0 ? o.items[0] : null;
                                    const isPublicWeb = o.source === 'PUBLIC_WEB';
                                    return (_jsxs("tr", { className: "hover:bg-slate-800/30 transition-colors", children: [_jsxs("td", { className: "p-4", children: [_jsx("span", { className: "font-bold text-white block", children: o.order_number }), _jsxs("span", { className: "text-[10px] text-slate-500 font-mono", children: [o.id.slice(0, 13), "..."] })] }), _jsx("td", { className: "p-4", children: isPublicWeb ? (_jsxs("span", { className: "inline-flex items-center gap-1 bg-blue-500/10 text-blue-400 border border-blue-500/20 px-2 py-0.5 rounded text-[10px] font-bold", children: [_jsx(Globe, { className: "w-3 h-3" }), "WEB"] })) : (_jsxs("span", { className: "inline-flex items-center gap-1 bg-purple-500/10 text-purple-400 border border-purple-500/20 px-2 py-0.5 rounded text-[10px] font-bold", children: [_jsx(Monitor, { className: "w-3 h-3" }), "TERMINAL"] })) }), _jsx("td", { className: "p-4 font-sans", children: item ? (_jsxs("div", { children: [_jsx("span", { className: "font-semibold text-white block text-xs", children: item.product_name }), _jsxs("span", { className: "text-[11px] text-cyan-400 font-mono", children: [item.volume_ml, "ml \u00D7 ", item.quantity, " (CH ", item.channel_id, ")"] })] })) : (_jsx("span", { className: "text-slate-500 italic", children: "No items" })) }), _jsxs("td", { className: "p-4 font-bold text-white text-xs", children: ["\u20B9", o.amount.toFixed(2)] }), _jsx("td", { className: "p-4", children: _jsx("span", { className: `inline-block px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${o.payment_status === 'PAID'
                                                        ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                                                        : o.payment_status === 'FAILED'
                                                            ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                                                            : 'bg-amber-500/20 text-amber-400 border border-amber-500/30'}`, children: o.payment_status }) }), _jsx("td", { className: "p-4", children: _jsxs("span", { className: `inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${o.order_status === 'DISPENSED'
                                                        ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/30'
                                                        : o.order_status === 'DISPENSING'
                                                            ? 'bg-blue-500/20 text-blue-300 border border-blue-500/30 animate-pulse'
                                                            : o.order_status === 'FAILED'
                                                                ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30'
                                                                : 'bg-slate-800 text-slate-300'}`, children: [o.order_status === 'DISPENSING' && _jsx(Droplets, { className: "w-3 h-3" }), o.order_status] }) }), _jsx("td", { className: "p-4 text-slate-400 text-[10px]", children: new Date(o.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) }), _jsxs("td", { className: "p-4 text-right space-x-2", children: [o.payment_status === 'PAID' && o.order_status !== 'DISPENSED' && (_jsx("button", { onClick: () => handleManualRefund(o.id, o.order_number), className: "text-amber-400 hover:text-amber-300 text-[11px] font-semibold hover:underline", title: "Issue manual refund", children: "Refund" })), _jsx("button", { onClick: () => setSelectedOrder(o), className: "text-cyan-400 hover:text-cyan-300 text-[11px] font-semibold hover:underline", children: "View" })] })] }, o.id));
                                })) : (_jsx("tr", { children: _jsx("td", { colSpan: 8, className: "p-8 text-center text-slate-500 font-sans text-xs", children: "No orders match your filter criteria." }) })) })] }) }) }), selectedOrder && (_jsx("div", { className: "fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4", children: _jsxs("div", { className: "bg-slate-900 border border-slate-800 w-full max-w-lg rounded-2xl shadow-2xl p-6 space-y-4 animate-in zoom-in-95", children: [_jsxs("div", { className: "flex justify-between items-center pb-3 border-b border-slate-800", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-bold text-white", children: selectedOrder.order_number }), _jsxs("span", { className: "text-xs text-slate-400 font-mono", children: ["ID: ", selectedOrder.id] })] }), _jsx("button", { onClick: () => setSelectedOrder(null), className: "text-slate-400 hover:text-white", children: "\u2715" })] }), _jsxs("div", { className: "space-y-3 text-xs text-slate-300 font-mono", children: [_jsxs("div", { className: "flex justify-between py-1 border-b border-slate-800", children: [_jsx("span", { className: "text-slate-500 font-sans", children: "Source" }), _jsx("span", { className: "font-bold text-white", children: selectedOrder.source || 'SYSTEM_1_TERMINAL' })] }), _jsxs("div", { className: "flex justify-between py-1 border-b border-slate-800", children: [_jsx("span", { className: "text-slate-500 font-sans", children: "Target Machine" }), _jsx("span", { className: "text-cyan-400 font-bold", children: selectedOrder.machine_code })] }), _jsxs("div", { className: "flex justify-between py-1 border-b border-slate-800", children: [_jsx("span", { className: "text-slate-500 font-sans", children: "Payment Status" }), _jsx("span", { className: "text-emerald-400 font-bold", children: selectedOrder.payment_status })] }), _jsxs("div", { className: "flex justify-between py-1 border-b border-slate-800", children: [_jsx("span", { className: "text-slate-500 font-sans", children: "Dispensing Status" }), _jsx("span", { className: "text-cyan-400 font-bold", children: selectedOrder.order_status })] }), _jsxs("div", { className: "flex justify-between py-1 border-b border-slate-800", children: [_jsx("span", { className: "text-slate-500 font-sans", children: "Authoritative Total" }), _jsxs("span", { className: "font-bold text-white text-sm", children: ["\u20B9", selectedOrder.amount.toFixed(2)] })] }), _jsxs("div", { className: "flex justify-between py-1", children: [_jsx("span", { className: "text-slate-500 font-sans", children: "Created At" }), _jsx("span", { children: new Date(selectedOrder.created_at).toLocaleString() })] })] }), _jsx("div", { className: "pt-3 border-t border-slate-800 flex justify-end", children: _jsx("button", { onClick: () => setSelectedOrder(null), className: "px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-xl text-xs font-semibold", children: "Close" }) })] }) }))] }));
}
